### ISSUE TITLE
TODO for the release

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#103]
In preparation for our first httomo/httomolib release, the following things needs of doing in order of priority:

- [x] Documentation for httomo that includes TomoPy yaml templates and links to TomoPy functions. We should add info how to run httomo and start documenting its functionality. 
- [x] [Yaml checker](https://github.com/DiamondLightSource/httomo/pull/101). This could be quite extensive and active development which will evolve with the feedback from the users. We will roll out the basic version of that to start with. 
- [x] Launcher. As the GPU development still in progress. The simple CPU launcher will suffice. 
- [x] [Logger](https://github.com/DiamondLightSource/httomo/pull/95)
- [x] Documentation for httomolib
- [x] Documentation for httomo that includes httomolib yaml templates and links to httomolib functions.
- [ ] Tests for all (preferably) TomoPy [templates](https://github.com/DiamondLightSource/httomo/tree/main/templates/tomopy). 

**Other pending but more "after release" issues**
- [ ] Inspection of padding (does it work?) and integration it into the meta as a decorator, similar to `pattern`
- [x] [Paganin filter reimplementation](https://github.com/DiamondLightSource/httomolib/issues/90).
- [ ]  Data stitching in httomolib
- [ ] Helical recon
- [ ] 4D data
- [ ] ....
