### ISSUE TITLE
TODO for HTTomo-GPU release

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#242]
For the GPU release of HTTomo we need the following tasks completed. Please feel free to modify and create separate issues where needed.

### Major (needs to be done)

- [x] #246
- [x] #244
- [x] #264
- [x] #245 
- [x] When no errors encountered in the benchmarks and the tests passing on `feature/transparent-file-store`, merge #198
- [x] Complete YAML checker and merge https://github.com/DiamondLightSource/httomo/pull/201
- [x] Merge #156 (not 100% sure if this should go later, but this is the earliest point it could be merged)
- [x] Right after the merge above, merge the following and see that tests pass for them all, as well as httomo:
    - [x] httomolib: https://github.com/DiamondLightSource/httomolib/pull/8
    - [x] httomolibgpu: https://github.com/DiamondLightSource/httomolibgpu/pull/113 
- [x] #252
- [x] #282 
- [x] #249
- [x] Check that the cashed kernel path is set https://github.com/DiamondLightSource/httomo/issues/243
- [x] Install httomo in `dls_sw`
- [x] Update and test launcher https://gitlab.diamond.ac.uk/scisoft/tomography/httomo_dls/-/issues/1 
- [x] Apply black or ruff formatting before the release
- [x] #227
- [x] #251 

### Minor (optional if there is time)
- [x] #261
- [x] #235 
- [x] #262 
- [x] #263
